INSERT INTO vaccinations (scope, childrenAgeInMonths, name, status, notes)
VALUES ('mandatory', '0', 'Hepatitis B', 'TO_ARRANGE', ''),
        ('mandatory', '0', 'BCG', 'TO_ARRANGE', ''),
        ('mandatory', '2', '6in1', 'TO_ARRANGE', ''),
        ('mandatory', '2', 'Pneumococci', 'TO_ARRANGE', ''),
        ('mandatory', '2', 'Rotavirus', 'TO_ARRANGE', ''),
        ('recommended', '2', 'Meningococci', 'TO_ARRANGE', ''),
        ('mandatory', '4', '6in1', 'TO_ARRANGE', ''),
        ('mandatory', '4', 'Pneumococci', 'TO_ARRANGE',''),
        ('mandatory', '4', 'Rotavirus', 'TO_ARRANGE',''),
        ('recommended','4', 'Meningococci', 'TO_ARRANGE',''),
        ('mandatory', '5 - 6', '6in1', 'TO_ARRANGE',''),
        ('mandatory', '5 – 6', 'Rotavirus', 'TO_ARRANGE',''),
        ('mandatory', '7', 'Hepatitis B', 'TO_ARRANGE',''),
        ('recommended', '7', 'Meningococci', 'TO_ARRANGE',''),
        ('mandatory', '13 – 15', 'MMR', 'TO_ARRANGE',''),
        ('mandatory', '13 – 15', 'Pneumococci', 'TO_ARRANGE',''),
        ('recommended', '13 - 15', 'Meningococci', 'TO_ARRANGE',''),
        ('recommended', '13 - 15', 'Chickenpox', 'TO_ARRANGE',''),
        ('recommended', '13 - 15', 'KZM', 'TO_ARRANGE',''),
        ('mandatory', '16 – 18', '6in1', 'TO_ARRANGE',''),
        ('recommended', '13 - 15', 'Chickenpox', 'TO_ARRANGE',''),
        ('recommended', '24', 'Hepatitis A', 'TO_ARRANGE',''),
        ('recommended', '30 - 36', 'Hepatitis A', 'TO_ARRANGE','');
